### ISSUE TITLE
Adicionar README ao Repositório

### ISSUE THREAD

**Issue by fernandogomesfg** [maicatheus/virtual-cycling-controller#1]
Olá Matheus,

Primeiramente, gostaria de expressar meus parabéns pelo incrível projeto que você compartilhou. Me deparei com ele através do Linkedin e fiquei impressionado com a inovação ao utilizar Python com Mediapipe, OpenCV e VGamePad. 

No entanto, observei que o repositório atualmente não possui um README. Sugiro adicionar um README ao repositório para facilitar a compreensão do projeto e permitir que outros desenvolvedores possam explorar o mesmo.

**Comment by maicatheus** [comment]
Olá, Fernando!

Valeu pela dica!!

Farei isso mesmo!

Um abraço, obrigado pelo feedback e que bom que gostastes do projeto!
