### ISSUE TITLE
Um dica, adicione versionamento das dependências para evitar problemas futuros

### ISSUE THREAD

**Issue by GuilhermeNobre** [maicatheus/virtual-cycling-controller#2]
Eu gostei muito do seu projeto pois já fiz alguns trabalhos usando mediapipe e da mesma forma que você fez, usando  onde os pontos estão para executar funções no código, muito bacana.

Recomendo você utilizar versionamento de arquivos para no futuro quando as dependências atualizarem seu código não dê problemas, fala isso por experiência usando a mediapipe que é bem problemática relação a algumas versões do Python e quando atualiza. Basta adicionar um arquivo chamado `"requirements.txt"` com as dependências do seu código abaixo

absl-py==2.0.0
attrs==23.1.0
cffi==1.16.0
contourpy==1.2.0
cycler==0.12.1
flatbuffers==23.5.26
fonttools==4.44.1
install==1.3.5
kiwisolver==1.4.5
matplotlib==3.8.1
mediapipe==0.10.8
numpy==1.26.2
opencv-contrib-python==4.8.1.78
opencv-python==4.8.1.78
packaging==23.2
Pillow==10.1.0
protobuf==3.20.3
pycparser==2.21
pyparsing==3.1.1
python-dateutil==2.8.2
six==1.16.0
sounddevice==0.4.6
vgamepad==0.1.0

e depois isso fazer o seguinte comando 

`pip install -r requirements.txt` 

dessa forma evita futuros problemas de versionamento e código será sempre funcional

**Comment by maicatheus** [comment]
Valeu Guilherme!!!!

Muito obrigado pela dica!

Farei isso o quanto antes!!!

Muito legal trabalhar com o Mediapipe..

Ele entrega os pontos e depois é pura geometria plana para efetuar alguns
cálculos como ângulo ou distância entre pontos!
hahahah

Novamente agradeço a dica!!!

**Comment by GuilhermeNobre** [comment]
Vlw, se um dia for fazer de avião me avisa, gosto muito do GTA V e MSFS tbm hahaha

**Comment by maicatheus** [comment]
Tou construindo hahahahA
Abraço!!!
